#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: YOUR_GOOGLE_CLIENT_ID
#            client-secret: YOUR_GOOGLE_CLIENT_SECRET
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            client-name: Google
#
#          facebook:
#            client-id: YOUR_FACEBOOK_CLIENT_ID
#            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
#            scope: email, public_profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            client-name: Facebook

#          linkedin:
#            client-id: YOUR_LINKEDIN_CLIENT_ID
#            client-secret: YOUR_LINKEDIN_CLIENT_SECRET
#            scope: r_liteprofile, r_emailaddress
#            redirect-uri: "{baseUrl}/login/oauth2/code/linkedin"
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#            client-name: LinkedIn
